backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "episodes"
    label: "Episodes"
    folder: "content/episodes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
  - name: "companies"
    label: "Companies"
    folder: "content/companies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - {
          label: "Image Background Color",
          name: "imageBackgroundColor",
          widget: "string",
        }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Episode Link", name: "episodeLink", widget: "string" }
      - { label: "Invest Link", name: "investLink", widget: "string" }
  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title (Person's title)", name: "title", widget: "string" }
      - { label: "Quote", name: "quote", widget: "markdown" }
      - { label: "Picture", name: "picture", widget: "image" }
  - name: "issuer_arrangements"
    label: "Issuer Arrangements"
    folder: "content/issuer_arrangements"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Issuer Name", name: "issuerName", widget: "string" }
      - {
          label: "Compensation Arrangement",
          name: "compensationArrangement",
          widget: "text",
        }
      - {
          label: "Prior Relationship with Issuer(s)",
          name: "priorRelationship",
          widget: "text",
        }
      - { label: "EDGAR Filings", name: "edgarFilings", widget: "string" }
  - name: "titan_arrangements"
    label: "Titan Arrangements"
    folder: "content/titan_arrangements"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titan Name", name: "titanName", widget: "string" }
      - { label: "Issuer Name", name: "issuerName", widget: "string" }
      - {
          label: "Compensation Arrangement",
          name: "compensationArrangement",
          widget: "text",
        }
      - {
          label: "Prior Relationship with Issuer(s)",
          name: "priorRelationship",
          widget: "text",
        }
      - {
          label: "No Securities Advice Disclaimer",
          name: "noSecuritiesAdvise",
          widget: "text",
          default: "At no time does [Titan] [or [insert affiliate name(s) if applicable]] provide investment advice, endorsement, analysis, or recommendations with respect to securities.",
        }
