backend:
  name: git-gateway
  branch: decap-cms # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "episodes"
    label: "Episodes"
    folder: "content/episodes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
  - name: "companies"
    label: "Companies"
    folder: "content/companies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Episode Link", name: "episodeLink", widget: "string" }
      - { label: "Invest Link", name: "investLink", widget: "string" }
  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title (Person's title)", name: "title", widget: "string" }
      - { label: "Quote", name: "quote", widget: "markdown" }
      - { label: "Picture", name: "picture", widget: "image" }
